### ISSUE TITLE
Framerate dropping minutes into gameplay (V.2.4.0)

### ISSUE THREAD

**Issue by B00ie23** [TheNexusAvenger/Nexus-VR-Character-Model#16]
I'm using an Oculus Quest 2 w/ Oculus Link, both headset and controllers are stock. This issue occurs on any experience (and in studio) that is running V.2.4.0.
The issue concerns the framerate dropping during gameplay. It isn't noticeable within the first minute of playing the experience in VR, but after some time, the framerate dropping start to become noticeable.

https://user-images.githubusercontent.com/45867359/192961681-23ab4f96-16ac-4a94-b8be-6730b6aba18c.mp4

_(Apologies for the poor text timing, Window's Video Editor is extremely limited.)_
The test environment shown in the attached (hopefully) video has no scripts other than NVR's loader and MainModule (both obtained from here,) the environment otherwise consists only of parts, meshes, and textures.

I did try an experience that does not have NVR, as well as trying earlier versions, and my framerate remained at a stable 72 FPS average. (72 FPS is Oculus Link's default framerate cap.)

**Comment by TheNexusAvenger** [comment]
I've heard claims that there were performance issues with VR in general since either Roblox release 544 or 545. This is the first claim that this is specific to Nexus VR Character Model V.2.4.0. If this problem is specific to the version, the problem will take some time to figure out: https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/compare/V.2.3.0..V.2.4.0

**Comment by TheNexusAvenger** [comment]
A problem has been found with Nexus VR Backpack which has been patched and has started rolling out to new servers. In order to keep the default Roblox backpack disabled, `SetCoreGuiEnabled` is looped in the backpack. With the latest release, this seems to have a performance problem. The following is an example brings Studio down to about 30 FPS from 80 FPS within a minute:
```lua
local StarterGui = game:GetService("StarterGui")
while true do
	StarterGui:SetCoreGuiEnabled(Enum.CoreGuiType.Backpack, false)
	task.wait()
end
```

If I start seeing positive results, I will close the issue. There won't be a new release for this issue this is specific to Nexus VR Backpack, but another change will result in V.2.4.1 being created.

**Comment by B00ie23** [comment]
I ran another test about half an hour ago, leaving the loader empty so it requests the latest modules available, and let studio run for the same time period. So far the performance is back to normal, and no drops has occurred during the test run.

I actually forgot the backpack had a release of it's own, my bad for not checking that.

**Comment by TheNexusAvenger** [comment]
> I actually forgot the backpack had a release of it's own, my bad for not checking that.

I don't blame you. While Nexus VR Backpack works standalone, I don't expect anyone to use it standalone any time soon. Most users for now will think the backpack is either native for Roblox or is part of Nexus VR Character Model.

Closing the issue since I am noticing performance is back to normal in new servers. Thanks for testing with a previous release to reduce the debugging work.
