### ISSUE TITLE
Seats cause the character to go nuts

### ISSUE THREAD

**Issue by DerpzDeNugget** [TheNexusAvenger/Nexus-VR-Character-Model#2]
Hey, I've been using your VR Character Model script for a while now and I've came to the realisation that when sitting on seats (not vehicle seats, regular old seats) and then exit, you start moving at unknown speeds. for some reason the head direction changes it. Here's a gif:
[Gyazo](https://gyazo.com/7ccc923914a8081683ea211160edaf6f)
[Another Gyazo - Might be a bit more clear](https://gyazo.com/85ec7812956b85767e72531752700d09)
Proof that the seat I sat in is a SEAT not a VEHICLESEAT
![image](https://user-images.githubusercontent.com/39784890/105098259-b6521800-5aa1-11eb-8685-880030d3380f.png)

(What I done there was touch a seat on the back of the car, then jumped off, which causes this bug to happen)
This happens with every seat which isn't a vehicle seat. I'm making a small shooting range and whenever i enter one of the seated shooting zones then jump out, This exact thing happens; And as said previously, It for some reason has the head control where you're going, Along with the fact that all Z axis control is inverted. Overall, It can really make you sick if you don't reset.
I'm unsure what caused it but I hope it'll be able to be fixed soon. Tell me if you want to ask questions or the sort.

**Comment by TheNexusAvenger** [comment]
From the video, it looks like you are using a jeep free model on what looks like a baseplate, which should be enough for me to make a repro file. It also looks like you are using smooth locomotion instead of teleport locomotion. Are you seeing this with just smooth locomotion, or teleport and smooth locomotion?

**Comment by DerpzDeNugget** [comment]
Hey,
Thanks for the quick reply! anyways...
From what I can tell (especially due to the movement) It's smooth locomotion only - Though quite frankly i'm unsure. If anything, It might also affect Teleport.
Though taking a good look at the gif, It seems like it's trying to keep the head in place at all times... Which is odd.
I might add that it's just a best bet to have a seat, As in the example I used the jeep as an example - I can clarify that this happens in all seat instances. It's not just the jeep, And it's not a VehicleSeat either - VehicleSeats are completely fine.

Update: I've added some an extra gif and an image to the original post for a broader and clearer explaination.

**Comment by TheNexusAvenger** [comment]
Smooth locomotion is missing quite a bit of functionality and testing, which is mainly because of how motion sick I get developing and testing it. Don't expect a fix for this in the near future from me. If you really need this functionality, it may be faster to create a pull request with the fix.
- If it is limited to smooth locomotion, investigate: https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/blob/master/src/Character/Controller/SmoothLocomotionController.lua
  - The teleport control may be a useful reference: https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/blob/master/src/Character/Controller/TeleportController.lua
- If it affects both, which I haven't experienced, investigate: https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/blob/master/src/Character/Controller/BaseController.lua

**Comment by DerpzDeNugget** [comment]
Alright - I'll close the issue and hope that I'll be able to figure out a fix.

**Comment by TheNexusAvenger** [comment]
I am going to keep the issue open as it is an active issue. Just because I am not guaranteeing a fix doesn't mean it is resolved.

**Comment by DerpzDeNugget** [comment]
Ah.. Alright. Not that familiar with Github so sorry about that.

**Comment by DerpzDeNugget** [comment]
Okay, So i've figured out that this *is* an issue with teleporting, and *works the same way*. How it happens I don't know, But atleast I can confirm that it is an issue with both controllers.

**Comment by TheNexusAvenger** [comment]
I realized that I wasn't testing this correctly. I test teleporting out of seats not realizing that the A button was active in teleport mode as well. This has been fixed in the master branch and will release in version V.2.0.1 soon.
