### ISSUE TITLE
It fails to reflect the clients behavior on the server side like IK hands movement 

### ISSUE THREAD

**Issue by YTDevBud** [TheNexusAvenger/Nexus-VR-Character-Model#26]
am using Pc Vr and the headset is Rift S the nexus mod seems to work properly  my issue is that it fails to reflect the clients behavior on the server like there ik hands movement and such i was wandering maybe i missed some thing on the api is there a way to enable this and if so.

**Comment by TheNexusAvenger** [comment]
That isn't a bug. The server's only role is to replicate the movement to other clients.

**Comment by YTDevBud** [comment]
oky i see my apologies thanks

**Comment by YTDevBud** [comment]
> That isn't a bug. The server's only role is to replicate the movement to other clients.

well is there a way to replicate this hand positions to the server because if the client is traying to interact with something on the server side this wont take effect

**Comment by TheNexusAvenger** [comment]
What are you trying to do? Anything related to physics is handled by the client, not the server.

**Comment by YTDevBud** [comment]
some physics based interactions like the character hand knocking a stack of parts

**Comment by TheNexusAvenger** [comment]
Moving the character on the server isn't going to help with that use case because of 2 reasons:
1. Physics are handled by the client. Not only does this reduce server load, but it reduces any delay the player would see.
2. Hands + arms are uncollidable. I don't remember if Roblox still locks this down or not. In the case they do, cloning and welding the relevant parts would give you the functionality you want.
