### ISSUE TITLE
Can Walk through places in smooth locomotion smooth locomotion has no turning theres no jumping

### ISSUE THREAD

**Issue by casennthe05** [TheNexusAvenger/Nexus-VR-Character-Model#3]
i can walk through walls with smooth locomotion i can not turn with smooth loco motion and there is no jumping

**Comment by TheNexusAvenger** [comment]
I have covered 2 of the 3 concerns in a DM with another developer.
> In general, the smooth location is missing a lot of functionality because of how motion sick I get developing and testing it. As-is, Oculus Rift S users would be able to get this functionality because the right thumbstick is completely unused, but HTC Vive, Microsoft Mixed Reality, etc users have the problem of the right touchpad being used for buttons, such as A to leave a seat. If you want this functionality to exist, I request that you contribute that to the GitHub repository for Nexus VR Character Model.

The concerns you raise aren't really bugs but are more lacking of features. There are no checks for walls, there is no jumping simulated, and there is no support for rotating. As covered in the quote and in the template for the GitHub issue, which I am guessing was just deleted because no headset information was included, I won't be addressing it any time soon.

**Comment by TheNexusAvenger** [comment]
I have gotten a lot of messages regarding adding this functionality. I have gone in with another developer to offer **80K Robux** ($280 in DevEx) for this functionality, split 50K Robux from me and 30K Robux from another development team.
https://devforum.roblox.com/t/80k-nexus-vr-scripter-open/1022099

I can't speak much for the team's requirements for their game, but I *strongly* suggest reaching out to them first because they have a proper game to test the implementation and so that their job can properly be claimed. For my requirements, I am looking for:
* Proper code changes that lead to this GitHub issue being closed, so adding jumping, snap-rotating, and collision checks.
* The code style to be consistent with the existing code.
* The complete code to be submitted as a pull request to this repository, created as a fork.

Once a pull request is created, I will validate the changes in a few of my games using an Oculus Rift S and Microsoft Mixed Reality. After the pull request is merged, I will private message information about my payment. Make sure to either include your username on your GitHub profile (including username) or in the pull request body.

**Comment by TheNexusAvenger** [comment]
I am retracting my bounty because I came up with a different method on how to solve this that resolved the collision issue and improves jumping. Snap-turning while using smooth locomotion was also added, but is only available for controllers that have dedicated A/B buttons and joysticks.
https://devforum.roblox.com/t/nexus-vr-character-model-open-source/109055/54

Once this gets merged to master and released to everyone, I would close this issue.

**Comment by TheNexusAvenger** [comment]
V.2.1.0 is live and addresses these limitations. If you are already using the V2 loader, then no actions are required to upgrade since servers will pull the latest version.
https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/releases/tag/V.2.1.0

Closing this issue since it is resolved.
