### ISSUE TITLE
V2.10.x Movement going different directions when physically rotating

### ISSUE THREAD

**Issue by B00ie23** [TheNexusAvenger/Nexus-VR-Character-Model#43]
I use a Quest 2 + VR Air Bridge to connect my headset to my PC. I experience this issue in _almost_ all experiences.

Basically, when I rotate physically to move in different directions, it appears to be having a "double effect" causing movement to behave strange.
When facing left or right by 90 degrees, the character moves sideways _opposite_ of the calibrated forward-facing direction.
When facing backwards, the character also moves backwards _toward_ the calibrated forward-facing direction.

I've attempted countless ways to try and reproduce this on a fresh baseplate, both live and studio, from changing configurations, to using older modules. None of my attempts were successful in reproducing the behavior.
To make this even more troublesome (and even stranger to an extent,) not all experiences running V2.10 are having this issue.

Experiences that are affected by this:
- [Catalog Avatar Creator](https://www.roblox.com/games/7041939546) (and it's [Test Server](https://www.roblox.com/games/7061415250))
- [The Meme RV](https://www.roblox.com/games/5412621627)
- [R6 Dances](https://www.roblox.com/games/2592032536)
- [rainy day](https://www.roblox.com/games/4960160668)
- [Plaza Connect](https://www.roblox.com/games/5118029260)
- [Disaster Simulation](https://www.roblox.com/games/5141688035)
- [Koala Cafe](https://www.roblox.com/games/961426258)
There could be way more that are affected, but these are just a few.

Experiences that are __not__ affected by this:
- _Any experience with V2.9.0 or earlier_
- [Roblox Talent Show](https://www.roblox.com/games/10851599)
- [Innovation Inc. Spaceship](https://www.roblox.com/games/331811267) (and other Innovation Inc. experiences)
- [Bus Simulator](https://www.roblox.com/games/2091563160)
- [Kit Battle](https://www.roblox.com/games/6549663822)
There are probably more that remain unaffected, but these are just some.

https://github.com/TheNexusAvenger/Nexus-VR-Character-Model/assets/45867359/6c50853d-a2ed-4227-976b-8e7e41ddf2df

Note: On the first clip between `0:07-0:14`, and on the second clip between `0:30-0:37`, the thumbstick Y value is held forwards while physically rotating, the movement can be seen behaving differently between the two clips.

I'm thinking that something may be up with Roblox's default movement system. If that is the case, I can try to move this to the devforums, but I do not have permissions to post in bug reports there, especially because I am unable to reproduce this.

**Comment by TheNexusAvenger** [comment]
Game-specific issues like these are *probably* caused by 1 of 2 causes **that I can't address**:
1. The game has custom/modified ("Forked") PlayerScripts with outdated gamepad controls. Roblox does **NOT** encourage this.
2. The game has custom inputs either using CFraming or `Humanoid::MoveTo` calls. This is less common, but does exist.

V.2.10 moved to relying on Roblox's PlayerScripts to ensure feature parity of inputs. One game owner came up to me saying that Nexus VR Character Model does not work as expected with their forked PlayerScripts. **Nexus VR Character Model can't account for games using older/modified PlayerScripts that don't properly support VR.** Forking the PlayerScripts is highly discouraged by Roblox for this reason, and has been discouraged for nearly a decade.

For any games that have this issue, please report the issue to them with this GitHub Issue linked. Please re-open the issue if a game confirms they *don't* do any of these, but the few cases I've heard do involve forked PlayerScripts.
